development:
  adapter: postgresql
  encoding: unicode
  database: printshop
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: printshop_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: printshop_p
  pool: 5
  password: